spring.application.name=api-gateway

server.port=8080
# server.servlet.context-path=/api

logging.level.org.springframework=DEBUG

# Routing Configuration
# User
spring.cloud.gateway.server.routes[0].id=user-service
spring.cloud.gateway.server.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.routes[0].predicates[0]=Path=/user/**

# Payment
spring.cloud.gateway.server.routes[1].id=payment-service
spring.cloud.gateway.server.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.routes[1].predicates[0]=Path=/payment/**

# Order
spring.cloud.gateway.server.routes[2].id=order-service
spring.cloud.gateway.server.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.routes[2].predicates[0]=Path=/order/**

# Service Registry URL
eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka


