spring.application.name=api-gateway

server.port=8080
# server.servlet.context-path=/api

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG

spring.config.import=optional:configserver:http://localhost:8889/configserver

# Spring Cloud Discovery Locator (Dynamic Routing & Default Load Balancing)
spring.cloud.gateway.discovery.locator.enabled=true

# Making the URL service name lower case
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


